name: intl_phone_field
description: A customised Flutter TextFormField to input international phone number along with country code.
version: 3.1.0+1
homepage: https://github.com/vanshg395/intl_phone_field

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1 
  lints: ^2.0.0 

flutter:
  assets:
    - assets/flags/
